### 회원가입 요청
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "홍길똥",
  "studentId": 20221235,
  "password": "pw11223344",
  "nickname": "길똥이",
  "department": "IT미디어 공학과",
  "phone": "010-1234-5677"
}

### 로그인 요청
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "studentId": 20221234,
  "password": "pw11223344"
}

### 회원가입 실패 (비밀번호 규칙 미준수)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "이순신",
  "studentId": 20221235,
  "password": "1234567",
  "nickname": "순신이",
  "department": "경영학과",
  "phone": "010-9876-5432"
}

### 로그인 실패 (잘못된 비밀번호)
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "studentId": 20221234,
  "password": "wrongpassword"
}

### 메인 페이지 게시글 로딩 (해드립니다 2개, 해주세요 2개)
GET http://localhost:5000/api/posts/main
Content-Type: application/json

###

### 카테고리별 게시글 로딩 (예: IT)
GET http://localhost:5000/api/posts/category/IT
Content-Type: application/json

### 미술
GET http://localhost:5000/api/posts/category/ART
Content-Type: application/json

###

### IT 게시글 작성
POST http://localhost:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOtJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwic3R1ZGVudElkIjoyMDIyMTIzNSwiaWF0IjoxNzI3OTYyNzE4LCJleHAiOjE3Mjc5NjYzMTh9.50XTCmDFqg2NHVH-Udvm06DB7NDAogZjP5q5KUXx2CE

{
  "title": "코딩 해주세요",
  "content": "모르는 코딩 문제 부탁드려요.",
  "price": 10000,
  "category": "IT",
  "type": "해주세요",
  "imageUrl": "http://example.com/image.jpg"
}

### 미술 게시글 작성
POST http://localhost:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTU1ODEzLCJleHAiOjE3Mjc5NTk0MTN9.xGaalDa7G8aPWv66qBvanRbWU_47Fs2oJ5IJqH2Vmx4

{
  "title": "그림 그려주세요.",
  "content": "그림 그려주세요",
  "price": 10000,
  "category": "ART",
  "type": "해주세요",
  "imageUrl": "http://example.com/image.jpg"
}

### 게시글 상세 보기 
GET http://localhost:5000/api/posts/2
Content-Type: application/json

###

### 게시글 공감 (JWT 토큰 필요)
POST http://localhost:5000/api/posts/2/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY4NTQ3LCJleHAiOjE3Mjc5NzIxNDd9.ScTz_nn44heLZAZYkNhZ79M5RiQYGUAHQ6aP7Hu9aDc


### 공감 취소 
DELETE http://localhost:5000/api/posts/2/unlike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY4NTQ3LCJleHAiOjE3Mjc5NzIxNDd9.ScTz_nn44heLZAZYkNhZ79M5RiQYGUAHQ6aP7Hu9aDc

### 게시글 수정 
PUT http://localhost:5000/api/posts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY4OTU3LCJleHAiOjE3Mjc5NzI1NTd9.IiCKdKFwrscavYQ0Ehrj52pNcHupoTD_daGjFptM8fs

{
  "title": "수정된 게시글 제목",
  "content": "수정된 게시글 내용",
  "price": 50000,
  "category": "IT"
}

### 게시글 삭제 (JWT 토큰 필요)
DELETE http://localhost:5000/api/posts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY1ODAxLCJleHAiOjE3Mjc5Njk0MDF9.ufYgwByz_A5EpO3JcxKV0H-9Ivtfx-fSGjSD4BvstD8

### 댓글 작성 (JWT 토큰 필요)
POST http://localhost:5000/api/comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY3OTk3LCJleHAiOjE3Mjc5NzE1OTd9.DnGPEKutxLvk5rckrO7y0MTaGDMVEazSqITrNKY2tO8

{
  "content": "정말 유익한 글이네요! 감사합니다.",
  "postId": 2
}

### 댓글 삭제 
DELETE http://localhost:5000/api/comments/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY3OTk3LCJleHAiOjE3Mjc5NzE1OTd9.DnGPEKutxLvk5rckrO7y0MTaGDMVEazSqITrNKY2tO8


### 댓글 수정 
PUT http://localhost:5000/api/comments/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwic3R1ZGVudElkIjoyMDIyMTIzNCwiaWF0IjoxNzI3OTY3OTk3LCJleHAiOjE3Mjc5NzE1OTd9.DnGPEKutxLvk5rckrO7y0MTaGDMVEazSqITrNKY2tO8

{
  "content": "수정된 댓글 내용"
}
